export const URLS_LIST_REQUEST = 'URLS_LIST_REQUEST';
export const URLS_LIST_SUCCESS = 'URLS_LIST_SUCCESS';
export const URLS_LIST_FAIL = 'URLS_LIST_FAIL';

export const URLS_CREATE_REQUEST = 'URLS_CREATE_REQUEST';
export const URLS_CREATE_SUCCESS = 'URLS_CREATE_SUCCESS';
export const URLS_CREATE_FAIL = 'URLS_CREATE_FAIL';

export const URLS_UPDATE_REQUEST = 'URLS_UPDATE_REQUEST';
export const URLS_UPDATE_SUCCESS = 'URLS_UPDATE_SUCCESS';
export const URLS_UPDATE_FAIL = 'URLS_UPDATE_FAIL';

export const URLS_DELETE_REQUEST = 'URLS_DELETE_REQUEST';
export const URLS_DELETE_SUCCESS = 'URLS_DELETE_SUCCESS';
export const URLS_DELETE_FAIL = 'URLS_DELETE_FAIL';
